main: tk.bongostudios.yuujou.App
name: Yuujou
version: 0.1
description: A group plugin (badly coded)
commands:
   group:
      description: A multi-argument command for managing groups
      usage: "Usage: /group [help|create|remove|list|kick|invite|user|option] (...args)"
permissions:
  yuujou.create:
   description: Allows to create a group
   default: true
  yuujou.remove:
   description: Allows to remove a group
   default: op
  yuujou.list:
   description: Allows to list members of a group
   default: true
  yuujou.kick:
   description: Allows to kick members from a group
   default: true
  yuujou.user:
   description: Allows to know in what group the user is
   default: true
  yuujou.allowpvp:
   description: Allows to switch PVP in the group
   default: true
  yuujou.privateinfo:
   description: Allows to switch private info to the group
   default: true
  yuujou.*:
   description: Wildcard permission
   default: op
   children:
     yuujou.create: true
     yuujou.remove: true
     yuujou.list: true
     yuujou.kick: true
     yuujou.user: true
     yuujou.option: true